'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export default function ResourcesPage() {
  const [courses, setCourses] = useState<any[]>([])
  const [selected, setSelected] = useState<any>(null)
  const [message, setMessage] = useState('')
  useEffect(() => { void (async () => { const { data } = await createClient().from('courses').select('id,title,syllabus_url,live_class_title,live_class_date,live_class_time,live_class_url,live_recording_url'); setCourses(data ?? []); setSelected(data?.[0] ?? null) })() }, [])
  const update = (key: string, value: string) => setSelected((current: any) => ({ ...current, [key]: value }))
  const upload = async (file?: File) => { if (!file || !selected) return; if (file.type !== 'application/pdf') return setMessage('শুধু PDF আপলোড করুন।'); const path = `syllabus/${selected.id}-${Date.now()}.pdf`; const supabase = createClient(); const { error } = await supabase.storage.from('course-media').upload(path, file, { contentType: 'application/pdf' }); if (error) return setMessage('আপলোড ব্যর্থ হয়েছে।'); const { data } = supabase.storage.from('course-media').getPublicUrl(path); update('syllabus_url', data.publicUrl); setMessage('PDF আপলোড হয়েছে, এখন Save চাপুন।') }
  const save = async () => { if (!selected) return; const { error } = await createClient().from('courses').update({ syllabus_url: selected.syllabus_url, live_class_title: selected.live_class_title, live_class_date: selected.live_class_date || null, live_class_time: selected.live_class_time, live_class_url: selected.live_class_url, live_recording_url: selected.live_recording_url }).eq('id', selected.id); setMessage(error ? 'সেভ করা যায়নি।' : 'সিলেবাস ও Zoom তথ্য সেভ হয়েছে।') }
  return <main className="min-h-screen bg-slate-50 p-5 text-slate-900 sm:p-8"><div className="mx-auto max-w-4xl"><header className="flex items-center justify-between"><div><p className="text-sm font-bold text-emerald-600">অ্যাডমিন কনটেন্ট</p><h1 className="mt-1 text-3xl font-black">সিলেবাস ও Zoom Live ক্লাস</h1></div><a href="/dashboard" className="rounded-xl border bg-white px-4 py-2 text-sm font-bold">ড্যাশবোর্ডে ফিরুন</a></header><section className="mt-8 rounded-3xl border bg-white p-6 shadow-sm"><label className="text-sm font-bold">কোর্স<select value={selected?.id ?? ''} onChange={(e) => setSelected(courses.find((course) => String(course.id) === e.target.value))} className="mt-2 w-full rounded-xl border p-3">{courses.map((course) => <option key={course.id} value={course.id}>{course.title}</option>)}</select></label>{selected && <div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold sm:col-span-2">সিলেবাস PDF<label className="mt-2 flex cursor-pointer items-center justify-between rounded-xl border border-dashed p-4"><span className="text-xs text-slate-500">{selected.syllabus_url ? 'PDF যুক্ত আছে' : 'PDF নির্বাচন করুন'}</span><input type="file" accept="application/pdf" className="sr-only" onChange={(e) => upload(e.target.files?.[0])} /><span className="rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700">আপলোড</span></label></label><label className="text-sm font-bold sm:col-span-2">লাইভ ক্লাসের বিষয়<input value={selected.live_class_title ?? ''} onChange={(e) => update('live_class_title', e.target.value)} className="mt-2 w-full rounded-xl border p-3" /></label><label className="text-sm font-bold">তারিখ<input type="date" value={selected.live_class_date ?? ''} onChange={(e) => update('live_class_date', e.target.value)} className="mt-2 w-full rounded-xl border p-3" /></label><label className="text-sm font-bold">সময়<input value={selected.live_class_time ?? ''} onChange={(e) => update('live_class_time', e.target.value)} placeholder="রাত ৮:০০" className="mt-2 w-full rounded-xl border p-3" /></label><label className="text-sm font-bold sm:col-span-2">Zoom Meeting Link<input value={selected.live_class_url ?? ''} onChange={(e) => update('live_class_url', e.target.value)} placeholder="https://zoom.us/j/..." className="mt-2 w-full rounded-xl border p-3" /></label><label className="text-sm font-bold sm:col-span-2">ক্লাস রেকর্ডিং Link<input value={selected.live_recording_url ?? ''} onChange={(e) => update('live_recording_url', e.target.value)} className="mt-2 w-full rounded-xl border p-3" /></label><button onClick={save} className="rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white sm:col-span-2">Save করুন</button></div>}{message && <p className="mt-4 text-sm font-semibold text-emerald-700">{message}</p>}</section></div></main>
}
